<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.hasor</groupId>
        <artifactId>cobble-parent</artifactId>
        <version>4.6.2-SNAPSHOT</version>
    </parent>

    <!-- Maven Info -->
    <artifactId>cobble-net</artifactId>
    <packaging>jar</packaging>

    <!-- Project Info -->
    <name>Cobble Net</name>
    <description>a aio Socket util.</description>

    <developers>
        <developer>
            <name>赵永春(Mr.Zhao)</name>
            <email>zyc@hasor.net</email>
        </developer>
    </developers>

    <!-- 引用依赖 -->
    <dependencies>
        <dependency>
            <groupId>net.hasor</groupId>
            <artifactId>cobble-bytebuf</artifactId>
        </dependency>
        <dependency>
            <groupId>net.hasor</groupId>
            <artifactId>cobble-logging</artifactId>
        </dependency>

        <!-- ssh密钥解析(非强制依赖) -->
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk15on</artifactId>
            <version>1.70</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bctls-jdk15on</artifactId>
            <version>1.70</version>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>
